// The Sahaj Field Guide to Growth & Impact - Generated Data
// This file is auto-generated by build.js. Do not edit directly.
// To update content, edit the Markdown files in the content/ directory and run: node build.js

const PERSONAS = {
  "artisan": {
    "id": "artisan",
    "name": "Artisan",
    "years": "1-3 Years",
    "tagline": "Mastering the craft",
    "color": "#00b894",
    "order": 2,
    "mindset": "I can deliver high-quality work independently and understand the context around it.",
    "natureOfImpact": [
      "Individual → local team",
      "Feature-level ownership",
      "Craft excellence emerges"
    ],
    "successLooksLike": [
      "Strong engineering fundamentals",
      "Reliable delivery",
      "Beginning to influence solutions, not just implement them"
    ],
    "explicitExpectation": []
  },
  "catalyst": {
    "id": "catalyst",
    "name": "Catalyst",
    "years": "4-8 Years",
    "tagline": "Sparking change & unblocking",
    "color": "#0984e3",
    "order": 3,
    "mindset": "I actively improve outcomes by shaping solutions, influencing people, and unblocking systems.",
    "natureOfImpact": [
      "Team-level",
      "Problem-space ownership",
      "Visible consulting behavior"
    ],
    "successLooksLike": [
      "Teams move faster and clearer because of you",
      "Ambiguity reduces when you engage",
      "Others trust your judgment"
    ],
    "explicitExpectation": []
  },
  "explorer": {
    "id": "explorer",
    "name": "Explorer",
    "years": "0-1 Years",
    "tagline": "Learning the terrain",
    "color": "#6c5ce7",
    "order": 1,
    "mindset": "I am learning how things are done, why they are done this way, and how to contribute safely.",
    "natureOfImpact": [
      "Individual",
      "Task-focused",
      "High learning velocity, low risk-taking"
    ],
    "successLooksLike": [
      "Becoming dependable",
      "Learning Sahaj's engineering and consulting culture",
      "Asking good questions early"
    ],
    "explicitExpectation": []
  },
  "multiplier": {
    "id": "multiplier",
    "name": "Multiplier",
    "years": "8-12 Years",
    "tagline": "Scaling impact via others",
    "color": "#e17055",
    "order": 4,
    "mindset": "My success is measured by how effective my team becomes without my constant presence.",
    "natureOfImpact": [
      "Single team (end-to-end)",
      "Capability multiplication",
      "Delivery + people + client outcomes"
    ],
    "successLooksLike": [],
    "explicitExpectation": [
      "Leads one team",
      "Owns team health, delivery, consulting quality, and technical bar"
    ]
  },
  "strategist": {
    "id": "strategist",
    "name": "Strategist",
    "years": "12+ Years",
    "tagline": "Shaping the long-term vision",
    "color": "#2d3436",
    "order": 5,
    "mindset": "I shape direction, culture, and growth beyond individual teams or projects.",
    "natureOfImpact": [
      "Account-level / org-level",
      "Long-term, compounding impact"
    ],
    "successLooksLike": [],
    "explicitExpectation": [
      "Leads accounts",
      "Drives Sahaj's growth, reputation, and strategic direction"
    ]
  }
};

const CAPABILITIES = {
  "communication": {
    "id": "communication",
    "name": "Communication & Influence",
    "question": "How far your impact travels",
    "order": 5,
    "description": "Clarity, facilitation, reach, and reputation",
    "intro": "This capability area captures the ability to: - Communicate clearly and with intent - Facilitate discussions and drive decisions - Build strong stakeholder relationships - Influence without authority - Represent Sahaj internally and externally Stakeholder management, relationship building, and influence live here because they determine reach, not ownership. As impact grows, communication expands beyond: - Team → multiple teams - Project → account - Internal → industry and ecosystem This includes contributions such as: - Community events - Conference talks - Hiring and proposals - Thought leadership",
    "note": null
  },
  "consulting": {
    "id": "consulting",
    "name": "Consulting",
    "question": "How well you clarify problems and shape solutions",
    "order": 2,
    "description": "Problem understanding, ambiguity removal, solution shaping, stakeholder partnership",
    "intro": "Consulting captures the ability to: - Understand problems beyond tickets and stories - Remove ambiguity - Reframe vague asks into solvable problem statements - Propose options and explain trade-offs - Help stakeholders make better decisions This capability area exists because delivery alone has a natural ceiling in a consulting organisation. Some engineers primarily execute well-defined work. Others actively shape what should be built and why. Both are valuable — but they are not the same kind of impact. Growth at Sahaj requires moving from order-taking to problem ownership.",
    "note": "This bucket is the clearest differentiator between delivery-only contribution and consulting-led impact. Many people believe they are doing consulting; the bullets below make it very hard to claim that without evidence."
  },
  "delivery": {
    "id": "delivery",
    "name": "Delivery Excellence",
    "question": "How reliably and sustainably value is delivered",
    "order": 3,
    "description": "Predictable, sustainable delivery of value",
    "intro": "Delivery Excellence reflects Sahaj's belief that: - Predictability matters more than heroics - Sustainable pace matters more than short-term speed - Good delivery is a system property, not an individual trait This capability area includes: - Story, feature, and milestone ownership - Risk management and dependency handling - Agile practices as principles, not rituals - Making trade-offs between scope, time, and quality explicit At higher levels, Delivery Excellence means improving how delivery works for others, not just getting your own work done.",
    "note": "Delivery excellence is not about speed alone. It is about reliability, predictability, and sustainability. This bucket prevents heroics from being mistaken for maturity."
  },
  "mentorship": {
    "id": "mentorship",
    "name": "Mentorship & Talent Growth",
    "question": "Who grows because of you",
    "order": 4,
    "description": "Growing people and teams",
    "intro": "Sahaj is a people-driven organisation. This capability area exists to make people impact explicit and visible. Mentorship & Talent Growth includes: - Coaching and teaching - Knowledge sharing - Feedback and conflict resolution - Creating psychologically safe, high-trust environments - Building teams that are strong even in your absence At senior levels, impact is measured less by what you personally deliver and more by the capability you grow around you.",
    "note": null
  },
  "technical": {
    "id": "technical",
    "name": "Technical Delivery",
    "question": "How well you build systems",
    "order": 1,
    "description": "Engineering craft, execution quality, and technical excellence",
    "intro": "Technical Delivery captures the quality of engineering judgment and execution. This capability area reflects Sahaj's belief that: - Engineering excellence is foundational - Clean code, sound design, and maintainability are non-negotiable - Polyglot capability is expected — backend, frontend, data, and infrastructure are part of the same system Technical Delivery is not about cleverness or volume of code. It is about building the right thing well, making appropriate trade-offs, and leaving systems healthier than you found them. At higher levels, this shifts from writing great code to setting technical direction and raising the bar for others.",
    "note": "This bucket is intentionally deep. Technical excellence is the foundation, but not the sole driver of growth at Sahaj. The bullets below are not exhaustive tasks; they describe habits, judgment, and quality bar."
  }
};

const EXPECTATIONS = {
  "technical": {
    "artisan": {
      "expectations": [
        "Independently implements stories end-to-end",
        "Breaks down stories into logical implementation steps",
        "Writes clean, readable, and maintainable code",
        "Applies SOLID principles and common design patterns where appropriate",
        "Writes unit and integration tests by default",
        "Uses meaningful naming and structure",
        "Debugs functional, integration, and environment issues independently",
        "Works across backend, frontend, data pipelines, and infra as needed",
        "Understands service boundaries and data flows",
        "Reviews peers' PRs with specific, actionable feedback",
        "Refactors code opportunistically while delivering features",
        "Understands basic performance bottlenecks",
        "Uses logs, metrics, and alerts effectively",
        "Follows secure coding practices",
        "Keeps implementation aligned with agreed design and acceptance criteria",
        "Takes responsibility for defects introduced by their code"
      ],
      "selfAssessment": [
        "Would someone unfamiliar with the code understand it easily?",
        "Do I improve code quality even when not explicitly asked?",
        "Can I explain why I chose this implementation?"
      ]
    },
    "catalyst": {
      "expectations": [
        "Designs solutions for complex, ambiguous, or cross-cutting requirements",
        "Breaks down large problem spaces into coherent technical approaches",
        "Anticipates edge cases, failure modes, and operational risks",
        "Makes deliberate architectural and design trade-offs",
        "Evaluates build vs buy decisions",
        "Leads technical discussions and design reviews",
        "Documents designs and rationale clearly",
        "Improves test strategy (not just coverage)",
        "Introduces better abstractions when needed",
        "Spots and addresses technical debt early",
        "Improves system observability and debuggability",
        "Considers performance, cost, and reliability together",
        "Guides others through complex debugging",
        "Aligns technical decisions with long-term system health",
        "Coaches others on technical reasoning, not just solutions"
      ],
      "selfAssessment": [
        "Do people seek my input for non-trivial technical decisions?",
        "Do I proactively prevent problems rather than react to them?",
        "Am I improving the system beyond my assigned scope?"
      ]
    },
    "explorer": {
      "expectations": [
        "Understands core programming constructs and language idioms",
        "Learns frameworks, libraries, and tools used in the project",
        "Sets up local development environment with help",
        "Implements small, well-defined tasks with guidance",
        "Writes correct but often linear or naive solutions",
        "Learns and follows coding standards and formatting rules",
        "Understands basic Git workflows (commit, pull, push, rebase)",
        "Uses logs and debuggers to investigate issues",
        "Writes unit tests when explicitly asked",
        "Fixes bugs with clear reproduction steps",
        "Responds constructively to PR feedback",
        "Improves code based on review comments",
        "Understands system architecture only at a conceptual level",
        "Avoids obvious regressions when making changes",
        "Learns basic security hygiene (secrets, credentials)"
      ],
      "selfAssessment": [
        "Can I complete a small task without repeated clarification?",
        "Do I understand what my code changes affect?",
        "Do I rely heavily on others to debug issues?"
      ]
    },
    "multiplier": {
      "expectations": [
        "Defines technical direction for teams or programs",
        "Establishes shared patterns, libraries, and standards",
        "Introduces platforms or accelerators reused across teams",
        "Improves developer productivity at scale",
        "Prevents systemic technical debt across projects",
        "Reviews and influences designs beyond own team",
        "Drives large-scale refactoring or modernization initiatives",
        "Balances innovation with platform stability",
        "Anticipates future technical needs and risks",
        "Aligns technical strategy with business direction",
        "Mentors others in advanced engineering concepts",
        "Raises the overall engineering quality bar",
        "Acts as a technical escalation point"
      ],
      "selfAssessment": [
        "Has my work eliminated recurring technical problems?",
        "Are multiple teams benefiting from my decisions?",
        "Do my technical choices scale beyond a single engagement?"
      ]
    },
    "strategist": {
      "expectations": [
        "Shapes org-wide technical vision and principles",
        "Defines long-term architectural direction",
        "Balances innovation, cost, risk, and sustainability",
        "Anticipates industry and technology shifts",
        "Sets and protects Sahaj's technical culture",
        "Makes high-impact, irreversible technical decisions responsibly",
        "Ensures coherence across systems and platforms",
        "Invests in long-term technical capability",
        "Acts as custodian of Sahaj's technical reputation",
        "Represents Sahaj's technical thinking externally"
      ],
      "selfAssessment": [
        "Will these decisions still be correct in several years?",
        "Am I protecting the organisation from long-term technical harm?",
        "Do I think beyond current clients and delivery pressures?"
      ]
    }
  },
  "consulting": {
    "artisan": {
      "expectations": [
        "Asks \"why\" behind stories, not just \"how\"",
        "Identifies gaps, contradictions, or missing requirements",
        "Understands basic business and domain context",
        "Suggests incremental improvements to proposed solutions",
        "Flags ambiguity proactively to team or leads",
        "Understands constraints such as timelines, cost, or regulations",
        "Connects individual stories to broader features",
        "Engages stakeholders with support",
        "Begins to think in trade-offs"
      ],
      "selfAssessment": [
        "Do I challenge unclear asks respectfully?",
        "Can I articulate the business problem, not just the ticket?",
        "Do I surface ambiguity early?"
      ]
    },
    "catalyst": {
      "expectations": [
        "Drives problem framing discussions end-to-end",
        "Reframes vague asks into clear, solvable problem statements",
        "Separates symptoms from root causes",
        "Proposes multiple solution options",
        "Clearly articulates trade-offs (tech, cost, risk, time)",
        "Helps stakeholders make informed decisions",
        "Pushes back when asks are misaligned or risky",
        "Reduces ambiguity for the entire team",
        "Handles conflicting stakeholder priorities",
        "Acts as a thought partner, not an order-taker",
        "Maintains trust while challenging assumptions",
        "Owns solutioning outcomes"
      ],
      "selfAssessment": [
        "Do stakeholders come to me for thinking or only for updates?",
        "Do discussions become clearer because I'm involved?",
        "Can I handle disagreement without escalation?"
      ]
    },
    "explorer": {
      "expectations": [
        "Listens carefully to problem statements without jumping to solutions",
        "Seeks clarification when requirements are unclear or inconsistent",
        "Asks basic questions to understand context",
        "Understands assigned tasks within the immediate feature scope",
        "Relies on others to define approach",
        "Accepts given constraints without challenging them",
        "Learns client or domain vocabulary gradually",
        "Escalates ambiguity rather than resolving it"
      ],
      "selfAssessment": [
        "Do I mostly wait for clarity or actively seek it?",
        "Can I explain the problem in my own words?",
        "Do I understand why this work matters?"
      ]
    },
    "multiplier": {
      "expectations": [
        "Leads solutioning for complex, high-ambiguity engagements",
        "Handles unclear or shifting goals with confidence",
        "Aligns multiple stakeholders toward a shared direction",
        "Anticipates stakeholder needs before they are stated",
        "Coaches others in consulting and problem-framing skills",
        "Navigates politics and power dynamics effectively",
        "Builds long-term stakeholder trust",
        "Shapes engagement direction beyond immediate scope",
        "Represents Sahaj as a trusted advisor"
      ],
      "selfAssessment": [
        "Do I influence direction beyond my formal role?",
        "Are others learning consulting skills by working with me?",
        "Can I operate effectively in politically complex environments?"
      ]
    },
    "strategist": {
      "expectations": [
        "Shapes Sahaj's consulting philosophy and approach",
        "Advises senior leadership and strategic clients",
        "Handles multi-year, multi-stakeholder problem spaces",
        "Defines standards for problem framing and engagement",
        "Influences how Sahaj is perceived in the ecosystem",
        "Sets the bar for consulting excellence"
      ],
      "selfAssessment": [
        "Am I trusted for judgment, not just expertise?",
        "Do my decisions shape Sahaj's long-term reputation?"
      ]
    }
  },
  "delivery": {
    "artisan": {
      "expectations": [
        "Owns stories end-to-end",
        "Estimates work reasonably",
        "Delivers predictably within commitments",
        "Tracks progress transparently",
        "Flags risks early",
        "Understands dependencies",
        "Participates actively in planning and retrospectives",
        "Adjusts plans when reality changes",
        "Maintains sustainable pace"
      ],
      "selfAssessment": [
        "Can others depend on my commitments?",
        "Do I manage my work or react to it?"
      ]
    },
    "catalyst": {
      "expectations": [
        "Owns epics or milestones",
        "Manages cross-team dependencies",
        "Identifies and mitigates delivery risks proactively",
        "Makes scope, time, and quality trade-offs explicit",
        "Improves delivery flow and predictability",
        "Champions agile principles, not just rituals",
        "Aligns delivery with business priorities",
        "Balances speed with quality and sustainability"
      ],
      "selfAssessment": [
        "Do I improve how work flows through the system?",
        "Do I make trade-offs visible and explicit?"
      ]
    },
    "explorer": {
      "expectations": [
        "Completes assigned tasks on time with support",
        "Understands sprint goals and commitments",
        "Learns agile basics and ceremonies",
        "Communicates blockers early",
        "Relies on others to manage scope and priorities"
      ],
      "selfAssessment": [
        "Do I reliably finish what I commit to?",
        "Do I communicate issues early or late?"
      ]
    },
    "multiplier": {
      "expectations": [
        "Improves delivery health across teams",
        "Introduces delivery practices that stick",
        "Coaches teams on delivery planning and execution",
        "Balances multiple streams of work",
        "Prevents burnout and chaos",
        "Improves predictability at scale"
      ],
      "selfAssessment": [
        "Has delivery become easier or harder because of me?",
        "Do teams feel safer and more predictable?"
      ]
    },
    "strategist": {
      "expectations": [
        "Shapes org-wide delivery culture",
        "Balances portfolio-level priorities",
        "Protects long-term delivery capability",
        "Optimises for system-level outcomes",
        "Prevents systemic delivery dysfunction"
      ],
      "selfAssessment": [
        "Am I optimising for short-term output or long-term health?",
        "Do I think beyond individual projects?"
      ]
    }
  },
  "mentorship": {
    "artisan": {
      "expectations": [
        "Helps onboard new team members",
        "Shares knowledge generously",
        "Gives basic, constructive feedback",
        "Explains reasoning, not just answers",
        "Creates a welcoming environment"
      ],
      "selfAssessment": [
        "Do others feel safe asking me for help?",
        "Do I invest time in helping others learn?"
      ]
    },
    "catalyst": {
      "expectations": [
        "Mentors consistently over time",
        "Helps others develop independent judgment",
        "Resolves conflicts constructively",
        "Improves team dynamics",
        "Supports onboarding and ramp-up effectively",
        "Gives timely, actionable feedback"
      ],
      "selfAssessment": [
        "Have people grown because of my support?",
        "Do I invest in others' growth proactively?"
      ]
    },
    "explorer": {
      "expectations": [
        "Coachable and receptive to feedback",
        "Learns from peers",
        "Helps others when asked",
        "Takes responsibility for own learning"
      ],
      "selfAssessment": [
        "Do I actively seek feedback?",
        "Am I open to changing my approach?"
      ]
    },
    "multiplier": {
      "expectations": [
        "Develops talent at scale",
        "Builds strong, self-sufficient teams",
        "Creates learning structures and forums",
        "Coaches mentors",
        "Raises the overall capability bar"
      ],
      "selfAssessment": [
        "Is the team stronger even when I step away?",
        "Am I creating future leaders?"
      ]
    },
    "strategist": {
      "expectations": [
        "Shapes culture and values",
        "Sponsors high-potential talent",
        "Ensures long-term people growth",
        "Acts as a role model across the organisation"
      ],
      "selfAssessment": [
        "Am I building capability beyond my tenure?",
        "Do I think in terms of generations of talent?"
      ]
    }
  },
  "communication": {
    "artisan": {
      "expectations": [
        "Articulates ideas clearly",
        "Writes clear documentation",
        "Communicates progress and blockers proactively",
        "Adapts communication style to audience",
        "Summarises discussions accurately"
      ],
      "selfAssessment": [
        "Can I explain my thinking to non-technical audiences?",
        "Do my messages reduce confusion?"
      ]
    },
    "catalyst": {
      "expectations": [
        "Drives discussions to decisions",
        "Facilitates meetings and workshops effectively",
        "Summarises options, decisions, and next steps",
        "Handles disagreement constructively",
        "Influences through clarity and reasoning"
      ],
      "selfAssessment": [
        "Do discussions move forward because of me?",
        "Can I handle tough conversations calmly?"
      ]
    },
    "explorer": {
      "expectations": [
        "Communicates clearly in small settings",
        "Shares updates when asked",
        "Listens actively",
        "Avoids unnecessary jargon"
      ],
      "selfAssessment": [
        "Do people understand me the first time?",
        "Do I listen to understand?"
      ]
    },
    "multiplier": {
      "expectations": [
        "Influences across teams and contexts",
        "Represents Sahaj externally (talks, community, hiring, proposals)",
        "Shapes narratives and alignment",
        "Builds credibility beyond immediate teams"
      ],
      "selfAssessment": [
        "Do my ideas travel beyond my immediate context?",
        "Am I seen as a voice of clarity and trust?"
      ]
    },
    "strategist": {
      "expectations": [
        "Shapes Sahaj's voice and reputation",
        "Handles high-stakes communication",
        "Influences industry or ecosystem direction",
        "Builds long-term credibility"
      ],
      "selfAssessment": [
        "Am I trusted to speak for Sahaj?",
        "Do my words have long-term impact?"
      ]
    }
  }
};

const PERSONA_ORDER = ["explorer","artisan","catalyst","multiplier","strategist"];

const CAPABILITY_ORDER = ["technical","consulting","delivery","mentorship","communication"];
